FROM apache/airflow:2.8.1-python3.10

USER airflow

RUN pip install --no-cache-dir \
    fastf1 \
    pandas \
    sqlalchemy \
    psycopg2-binary \
    # Adicione essas duas linhas
    dbt-postgres==1.7.11 \
    astronomer-cosmos