name: 'f1_transform'
version: '1.0.0'
config-version: 2
profile: 'f1_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  f1_transform:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts
      tyre_degradation:
        +materialized: incremental
        +unique_key: ['year', 'circuit_key', 'compound']
      compound_evolution:
        +materialized: table
      compound_physical_evolution:
        +materialized: table
      circuit_tyre_profile:
        +materialized: table
