name: 'f1_transform'
version: '1.0.0'
config-version: 2
profile: 'f1_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"] # Confirme que esta linha existe
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_transform:
    +materialized: table
    staging:
      +schema: staging # Use o nome limpo do esquema
    marts:
      +schema: marts # Use o nome limpo do esquema